### ISSUE TITLE
The wallet say Requested method not found: transfer

### ISSUE THREAD

**Issue by eeeeLeeee** [ipbc-dev/ipbc-pool#1]
2018-Mar-07 09:58:55.378244 WARNING Requested method not found: getbalance
2018-Mar-07 09:58:55.547860 WARNING  Requested method not found: transfer
how to fix it?

**Comment by eeeeLeeee** [comment]
@npoolpw I notice that you have build a ipbc-pool. I what to ask that how to connect the pool system and the wallet? which wallet program I should use?   walletd is ok?

**Comment by npoolpw** [comment]
@eeeeLeeee just use simple wallet and run it as rpc server and then set simplewallet rpc port to pool config.
